export const courseData = [
    {
      image: require("./Courses/courses/development.png"),
      category: 'Development',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Learn Figma: This is some dummy text demonstrating the title',
      videoCount: 45,
      studentCount: '2154+',
      ratings: 4.9,
      price: 120.0,
    },
    {
      image: require("./Courses/courses/development.png"),
      category: 'Finance',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Master the Six Basic Rules of Investing by Robert Kiyosaki',
      videoCount: 45,
      studentCount: '2154+',
      ratings: 4.9,
      price: 120.0,
    },
    {
      image: require("./Courses/courses/development.png"),
      category: 'Graphic Design',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Learn Figma: This is some dummy text demonstrating the title',
      videoCount: 45,
      studentCount: '2154+',
      ratings: 4.9,
      price: 120.0,
    },
  {
    image: require("./Courses/courses/development.png"),
    category: 'Marketing',
    subjectImage: require("./Courses/courses/p4.jpg"),
    title: 'Learn Figma: This is some dummy text demonstrating the title',
    videoCount: 45,
    studentCount: '2154+',
    ratings: 4.9,
    price: 120.0,
  },
  {
    image: require("./Courses/courses/development.png"),
    category: 'Photography',
    subjectImage: require("./Courses/courses/p4.jpg"),
    title: 'Learn Figma: This is some dummy text demonstrating the title',
    videoCount: 45,
    studentCount: '2154+',
    ratings: 4.9,
    price: 120.0,
  },
  {
    image: require("./Courses/courses/development.png"),
    category: 'Fitness',
    subjectImage: require("./Courses/courses/p4.jpg"),
    title: 'Learn Figma: This is some dummy text demonstrating the title',
    videoCount: 45,
    studentCount: '2154+',
    ratings: 4.9,
    price: 120.0,
  },
];