export const courseData = [
    // Development Courses
    {
      id: 1,
      image: require("./Courses/courses/development.png"),
      category: 'Development',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Complete Web Development Bootcamp 2024',
      videoCount: 85,
      studentCount: '12,154+',
      ratings: 4.9,
      price: 149.99,
    },
    {
      id: 2,
      image: require("./Courses/courses/development.png"),
      category: 'Development',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'JavaScript Mastery: ES6+ and Beyond',
      videoCount: 62,
      studentCount: '8,321+',
      ratings: 4.8,
      price: 129.99,
    },
    {
      id: 3,
      image: require("./Courses/courses/development.png"),
      category: 'Development',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'React & Redux: Building Modern Web Applications',
      videoCount: 71,
      studentCount: '15,890+',
      ratings: 4.7,
      price: 189.99,
    },
    {
      id: 4,
      image: require("./Courses/courses/development.png"),
      category: 'Development',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Python Programming: From Basics to Advanced',
      videoCount: 92,
      studentCount: '21,543+',
      ratings: 4.9,
      price: 199.99,
    },
    {
      id: 5,
      image: require("./Courses/courses/development.png"),
      category: 'Development',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Full Stack MERN Development: Complete Guide',
      videoCount: 105,
      studentCount: '9,876+',
      ratings: 4.8,
      price: 179.99,
    },
    // Finance Courses
    {
      id: 6,
      image: require("./Courses/courses/development.png"),
      category: 'Finance',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Stock Market Trading: From Beginner to Pro',
      videoCount: 48,
      studentCount: '5,678+',
      ratings: 4.6,
      price: 159.99,
    },
    {
      id: 7,
      image: require("./Courses/courses/development.png"),
      category: 'Finance',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Personal Finance Management Masterclass',
      videoCount: 55,
      studentCount: '7,234+',
      ratings: 4.7,
      price: 89.99,
    },
    {
      id: 8,
      image: require("./Courses/courses/development.png"),
      category: 'Finance',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Cryptocurrency Trading Strategies 2024',
      videoCount: 42,
      studentCount: '4,521+',
      ratings: 4.5,
      price: 139.99,
    },
    {
      id: 9,
      image: require("./Courses/courses/development.png"),
      category: 'Finance',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Investment Banking: Complete Analysis',
      videoCount: 78,
      studentCount: '3,987+',
      ratings: 4.8,
      price: 249.99,
    },
    {
      id: 10,
      image: require("./Courses/courses/development.png"),
      category: 'Finance',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Real Estate Investment Masterplan',
      videoCount: 65,
      studentCount: '6,543+',
      ratings: 4.7,
      price: 169.99,
    },
    // Graphic Design Courses
    {
      id: 11,
      image: require("./Courses/courses/development.png"),
      category: 'Graphic Design',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Adobe Photoshop: Complete Guide 2024',
      videoCount: 82,
      studentCount: '11,234+',
      ratings: 4.9,
      price: 129.99,
    },
    {
      id: 12,
      image: require("./Courses/courses/development.png"),
      category: 'Graphic Design',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'UI/UX Design Principles and Practice',
      videoCount: 68,
      studentCount: '8,765+',
      ratings: 4.8,
      price: 149.99,
    },
    {
      id: 13,
      image: require("./Courses/courses/development.png"),
      category: 'Graphic Design',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Logo Design Masterclass',
      videoCount: 45,
      studentCount: '5,432+',
      ratings: 4.6,
      price: 89.99,
    },
    {
      id: 14,
      image: require("./Courses/courses/development.png"),
      category: 'Graphic Design',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Adobe Illustrator for Beginners',
      videoCount: 58,
      studentCount: '7,654+',
      ratings: 4.7,
      price: 119.99,
    },
    {
      id: 15,
      image: require("./Courses/courses/development.png"),
      category: 'Graphic Design',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Digital Art and Illustration',
      videoCount: 72,
      studentCount: '4,321+',
      ratings: 4.8,
      price: 139.99,
    },
    // Marketing Courses
    {
      id: 16,
      image: require("./Courses/courses/development.png"),
      category: 'Marketing',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Digital Marketing Strategy 2024',
      videoCount: 95,
      studentCount: '13,567+',
      ratings: 4.9,
      price: 179.99,
    },
    {
      id: 17,
      image: require("./Courses/courses/development.png"),
      category: 'Marketing',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Social Media Marketing Mastery',
      videoCount: 78,
      studentCount: '9,876+',
      ratings: 4.7,
      price: 149.99,
    },
    {
      id: 18,
      image: require("./Courses/courses/development.png"),
      category: 'Marketing',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'SEO & Content Marketing Excellence',
      videoCount: 82,
      studentCount: '7,654+',
      ratings: 4.8,
      price: 159.99,
    },
    {
      id: 19,
      image: require("./Courses/courses/development.png"),
      category: 'Marketing',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Email Marketing Campaigns',
      videoCount: 52,
      studentCount: '5,432+',
      ratings: 4.6,
      price: 99.99,
    },
    {
      id: 20,
      image: require("./Courses/courses/development.png"),
      category: 'Marketing',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Google Ads & Facebook Ads Mastery',
      videoCount: 68,
      studentCount: '8,765+',
      ratings: 4.7,
      price: 169.99,
    },
    // Photography Courses
    {
      id: 21,
      image: require("./Courses/courses/development.png"),
      category: 'Photography',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Professional Photography Masterclass',
      videoCount: 75,
      studentCount: '6,789+',
      ratings: 4.8,
      price: 139.99,
    },
    {
      id: 22,
      image: require("./Courses/courses/development.png"),
      category: 'Photography',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Portrait Photography Techniques',
      videoCount: 58,
      studentCount: '4,567+',
      ratings: 4.7,
      price: 119.99,
    },
    {
      id: 23,
      image: require("./Courses/courses/development.png"),
      category: 'Photography',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Landscape Photography Advanced Guide',
      videoCount: 62,
      studentCount: '3,456+',
      ratings: 4.9,
      price: 129.99,
    },
    {
      id: 24,
      image: require("./Courses/courses/development.png"),
      category: 'Photography',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Mobile Photography: Pro Techniques',
      videoCount: 45,
      studentCount: '8,901+',
      ratings: 4.6,
      price: 79.99,
    },
    {
      id: 25,
      image: require("./Courses/courses/development.png"),
      category: 'Photography',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Wedding Photography Business Guide',
      videoCount: 85,
      studentCount: '5,678+',
      ratings: 4.8,
      price: 189.99,
    },
    // Fitness Courses
    {
      id: 26,
      image: require("./Courses/courses/development.png"),
      category: 'Fitness',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Complete Home Workout Program',
      videoCount: 90,
      studentCount: '14,567+',
      ratings: 4.9,
      price: 99.99,
    },
    {
      id: 27,
      image: require("./Courses/courses/development.png"),
      category: 'Fitness',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Yoga for Beginners to Advanced',
      videoCount: 65,
      studentCount: '11,234+',
      ratings: 4.8,
      price: 89.99,
    },
    {
      id: 28,
      image: require("./Courses/courses/development.png"),
      category: 'Fitness',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Nutrition and Meal Planning Guide',
      videoCount: 72,
      studentCount: '9,876+',
      ratings: 4.7,
      price: 129.99,
    },
    {
      id: 29,
      image: require("./Courses/courses/development.png"),
      category: 'Fitness',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'Strength Training Fundamentals',
      videoCount: 85,
      studentCount: '7,654+',
      ratings: 4.8,
      price: 119.99,
    },
    {
      id: 30,
      image: require("./Courses/courses/development.png"),
      category: 'Fitness',
      subjectImage: require("./Courses/courses/p4.jpg"),
      title: 'HIIT Cardio Workout Series',
      videoCount: 55,
      studentCount: '6,543+',
      ratings: 4.6,
      price: 79.99,
    },
];